# Generated by Django 3.0.2 on 2020-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='UserID',
            field=models.CharField(max_length=10),
        ),
    ]
