# Generated by Django 3.0.2 on 2020-05-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200505_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindata',
            name='month',
            field=models.TextField(default='mar2020'),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='UserID',
            field=models.TextField(),
        ),
    ]
