# Generated by Django 3.0.2 on 2020-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200505_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('month', models.TextField(default='mar2020')),
                ('total', models.FloatField(default=0)),
                ('status', models.TextField(default='not paid')),
            ],
        ),
    ]
