# Generated by Django 3.0.2 on 2020-05-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_monthwise'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindata',
            name='day',
            field=models.TextField(default='0'),
        ),
    ]
